const express = require('express')
const server = express()
const route = require('./route')
const path = require('path')
const exp = require('constants')
const { url } = require('inspector')
const { urlencoded } = require('express')

server.use(express.urlencoded({ extended: true }))
server.use(route)
server.set('view engine', 'ejs')
server.set('views', path.join(__dirname, 'views'))
server.use(express.static('public'))

server.listen(5051, () => console.log('rodando'))
